Repository risingstar-bit/Compose-Community, pull requests merged in 2022-10, with the labels that each got.

#40 Create Hacktoberfest
  Hacktoberfest/Readme.md
Labels: Hacktoberfest-accepted, Hacktoberfest

#51 Moved weatherbit API key to properties file
  Projects/Android-Development/WeatherApp/app/build.gradle
  Projects/Android-Development/WeatherApp/app/src/main/java/com/example/weatherapp/MainActivity.java
  Projects/Android-Development/WeatherApp/build.gradle
Labels: Hacktoberfest-accepted, Hacktoberfest

#54 Added Technical Writting Skill
  Cheatsheets/Technical_writting_skills/Writting_flow_process.png
  Cheatsheets/Technical_writting_skills/technical_writting.md
Labels: Hacktoberfest-accepted, Hacktoberfest

#58 Added roadmaps for android development/DSA/Communication skills
  Roadmaps/Android/Android roadmap.txt
  Roadmaps/Android/android_developer_roadmap.png
  Roadmaps/Android/roadmap android.svg
  Roadmaps/Communication Skills/7Cs-of-communication-1.png
  Roadmaps/Communication Skills/four phases of learning.jpg
  Roadmaps/Communication Skills/roadmap for effective communication.pdf
  Roadmaps/Communication Skills/upgrading communication skills.png
  Roadmaps/DSA/Basic idea to start DSA.png
  Roadmaps/DSA/DSA from scratch.jpg
  Roadmaps/DSA/DSA guide 2021.pdf
  Roadmaps/DSA/complete roadmap dsa.png
Labels: Hacktoberfest-accepted, Hacktoberfest

#59 ABSA
  Projects/Machine Learning/Aspect Based sentiment analysis/Aspect Based Sentiment Analysis.ipynb
  Projects/Machine Learning/Aspect Based sentiment analysis/model.pkl
  Projects/Machine Learning/Aspect Based sentiment analysis/output.csv
  Projects/Machine Learning/Aspect Based sentiment analysis/readme.md
  Projects/Machine Learning/Aspect Based sentiment analysis/test.csv
  Projects/Machine Learning/Aspect Based sentiment analysis/train.csv
Labels: Hacktoberfest-accepted, Hacktoberfest

#63 Added Currency Converter Java Project
  Notes/DevOps/First-Docker-Container.md
  Projects/Java-Projects/Currency-Converter/Currency Converter.jar
  Projects/Java-Projects/Currency-Converter/README.md
  Projects/Java-Projects/Currency-Converter/lib/mysql-connector-java-8.0.25.jar
  Projects/Java-Projects/Currency-Converter/lib/unknown/binary/AbsoluteLayout/SNAPSHOT/AbsoluteLayout-SNAPSHOT.jar
  Projects/Java-Projects/Currency-Converter/nb-configuration.xml
  Projects/Java-Projects/Currency-Converter/nbactions.xml
  Projects/Java-Projects/Currency-Converter/pom.xml
  Projects/Java-Projects/Currency-Converter/src/main/java/com/mycompany/project/Converter.form
  Projects/Java-Projects/Currency-Converter/src/main/java/com/mycompany/project/Converter.java
  Projects/Java-Projects/Currency-Converter/src/main/java/com/mycompany/project/CryptoTrading.form
  Projects/Java-Projects/Currency-Converter/src/main/java/com/mycompany/project/CryptoTrading.java
  Projects/Java-Projects/Currency-Converter/src/main/java/com/mycompany/project/Menu.form
  Projects/Java-Projects/Currency-Converter/src/main/java/com/mycompany/project/Menu.java
  Projects/Java-Projects/Currency-Converter/src/main/java/com/mycompany/project/ShowValues.form
  Projects/Java-Projects/Currency-Converter/src/main/java/com/mycompany/project/ShowValues.java
  Projects/Java-Projects/Currency-Converter/src/main/java/com/mycompany/project/backend.java
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/Converter$1.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/Converter$2.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/Converter$3.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/Converter$4.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/Converter$5.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/Converter$6.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/Converter$7.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/Converter$8.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/Converter$9.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/Converter.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/Converter.form
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/CryptoTrading$1.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/CryptoTrading$2.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/CryptoTrading$3.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/CryptoTrading$4.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/CryptoTrading.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/CryptoTrading.form
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/Menu$1.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/Menu$2.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/Menu$3.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/Menu$4.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/Menu.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/Menu.form
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/ShowValues$1.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/ShowValues$10.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/ShowValues$11.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/ShowValues$12.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/ShowValues$13.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/ShowValues$2.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/ShowValues$3.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/ShowValues$4.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/ShowValues$5.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/ShowValues$6.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/ShowValues$7.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/ShowValues$8.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/ShowValues$9.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/ShowValues.class
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/ShowValues.form
  Projects/Java-Projects/Currency-Converter/target/classes/com/mycompany/project/backend.class
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#69 Update and rename technical_writting.md to technical_writing.md
  Cheatsheets/Technical_writting_skills/technical_writing.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest, beginner

#78 ADDED THE C++ FOLDER AND SOME CODE
  DSA/C++/Binary_heap.cpp
  DSA/C++/Merge_Sort.cpp
  DSA/C++/Quick_Sort.cpp
  DSA/C++/Selection_sort.cpp
  DSA/C++/binary_search_tree.cpp
  DSA/C++/quick_Sort_linked_list.cpp
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#79 Face Recognition using webcam
  Projects/Machine Learning/Face Recognition using webcam/DataCollection.py
  Projects/Machine Learning/Face Recognition using webcam/Images/git_logo.svg
  Projects/Machine Learning/Face Recognition using webcam/Images/github_logo.svg
  Projects/Machine Learning/Face Recognition using webcam/Images/opencv.svg
  Projects/Machine Learning/Face Recognition using webcam/Images/prateek1.jpg
  Projects/Machine Learning/Face Recognition using webcam/Images/prateek10.jpg
  Projects/Machine Learning/Face Recognition using webcam/Images/prateek11.jpg
  Projects/Machine Learning/Face Recognition using webcam/Images/prateek12.jpg
  Projects/Machine Learning/Face Recognition using webcam/Images/prateek13.jpg
  Projects/Machine Learning/Face Recognition using webcam/Images/prateek14.jpg
  Projects/Machine Learning/Face Recognition using webcam/Images/prateek15.jpg
  Projects/Machine Learning/Face Recognition using webcam/Images/prateek2.jpg
  Projects/Machine Learning/Face Recognition using webcam/Images/prateek3.jpg
  Projects/Machine Learning/Face Recognition using webcam/Images/prateek4.jpg
  Projects/Machine Learning/Face Recognition using webcam/Images/prateek5.jpg
  Projects/Machine Learning/Face Recognition using webcam/Images/prateek6.jpg
  Projects/Machine Learning/Face Recognition using webcam/Images/prateek7.jpg
  Projects/Machine Learning/Face Recognition using webcam/Images/prateek8.jpg
  Projects/Machine Learning/Face Recognition using webcam/Images/prateek9.jpg
  Projects/Machine Learning/Face Recognition using webcam/Images/python_logo.svg
  Projects/Machine Learning/Face Recognition using webcam/README.md
Labels: hacktoberfest-accepted, hacktoberfest

#86 Added two Javascript Projects
  Projects/Javascript Projects/Password Generator/index.html
  Projects/Javascript Projects/Password Generator/script.js
  Projects/Javascript Projects/Password Generator/style.css
  Projects/Javascript Projects/README.md
  Projects/Javascript Projects/WeatherMan - Weather App using API/index.html
  Projects/Javascript Projects/WeatherMan - Weather App using API/script.js
  Projects/Javascript Projects/WeatherMan - Weather App using API/style.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#64 added code of linked list
  DSA/cpp/linked list/linked_list_by_ratnesh_maurya.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#87 LinearSearch
  DSA/C++/ALgorithm/LinearSearch.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#83 DSA Codes
  DSA/C++/ALgorithm/Geometry Based/Skyline Heights(Geometry Based Problem).cpp
  DSA/C++/ALgorithm/Linked List/ReverseLinkedList.cpp
  Projects/Machine Learning/Face Recognition using webcam/README.md
Labels: hacktoberfest-accepted, hacktoberfest

#94 Sieve
  DSA/cpp/linked list/Sieve.cpp
Labels: Changed-Required

#111 Javascript Notes and Questions Added
  Notes/Javascript/JavaScript Complete Notes .pdf
  Notes/Javascript/JavaScript Interview Questions .pdf
  Notes/Javascript/Javascript Cheat Sheet .pdf
  Notes/Javascript/README.md
Labels: hacktoberfest-accepted, hacktoberfest

#115 Added Javascript Notes, Cheatsheets and Interview questions
  Cheatsheets/Javascript/Javascript Cheat Sheet .pdf
  Cheatsheets/Javascript/README.md
  Interview Questions/JavaScript Interview Questions .pdf
  Notes/Javascript Notes/JavaScript Complete Notes .pdf
  Notes/Javascript Notes/README.md
Labels: hacktoberfest-accepted, hacktoberfest

#119 Jaggered Array
  DSA/C++/Array/jaggeredArray.cpp
Labels: hacktoberfest

#121 added Bubble sort and 4 Leetcode Questions
  DSA/C++/ALgorithm/Bubble Sort/README.md
  DSA/C++/ALgorithm/Bubble Sort/bubble_sort.cpp
  DSA/C++/Array_leetcode/162_Find_Peak_Element.cpp
  DSA/C++/Array_leetcode/191_Number_of_1_Bits.cpp
  DSA/C++/Array_leetcode/442_duplicates.cpp
  DSA/C++/Array_leetcode/69_Sqrt(x).cpp
Labels: hacktoberfest-accepted, hacktoberfest

#122 INSERTION SORT
  DSA/C++/ALgorithm/INSERTION SORT/INSERTION_SORT.cpp
  DSA/C++/ALgorithm/INSERTION SORT/README.md
  DSA/C/ALGORITHM/SORTING/BUBBLE SORT/Bubble_sort.c
  DSA/C/ALGORITHM/SORTING/BUBBLE SORT/README.md
  DSA/C/LinkedList_Problem/REVERSE LINKED LIST/Reverse_list.c
  DSA/C/LinkedList_Problem/Remove_Duplicate_Node/Remove_Duplicate_Node.c
Labels: hacktoberfest-accepted, hacktoberfest

#129 Added 2 OpenCV projects(ORGANIZED PROPERLY)
  Projects/Machine Learning/Hill Climb Racing using OpenCV/HIll_Climb_Racing.ipynb
  Projects/Machine Learning/Hill Climb Racing using OpenCV/Readme
  Projects/Machine Learning/Temple Run using OpenCV/Readme
  Projects/Machine Learning/Temple Run using OpenCV/Temple_Run.ipynb
Labels: hacktoberfest-accepted

#131 Floyd_cycle_finding_algo
  DSA/C++/ALgorithm/Linked List/Floyd_cycle_finding_algo.cpp
  DSA/C++/Array_leetcode/386_Lexicographical_Numbers.cpp
Labels: hacktoberfest-accepted

#127 Added LCS Code
  DSA/C++/ALgorithm/Longest Common Subsequence/LCS.cpp
  DSA/C++/ALgorithm/Longest Common Subsequence/Readme.md
  DSA/C++/ALgorithm/Window Sliding/Readme.md
  DSA/C++/ALgorithm/Window Sliding/SlidingWindow.cpp
Labels: hacktoberfest-accepted

#130 Merge sort
  DSA/C/ALGORITHM/SORTING/Merge Sort/Merge_sort.c
  DSA/C/ALGORITHM/SORTING/Merge Sort/README.md
Labels: hacktoberfest-accepted

#137 Kadane Algorithm
  DSA/C++/ALgorithm/Kadane_algorithm/kadane_algo.cpp
  DSA/C++/ALgorithm/Kadane_algorithm/readme.md
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#139 Added 20_Valid Parenthesis
  DSA/C++/Array_leetcode/20_Valid_Parenthesis.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#136 Delete node from Linked list
  DSA/C/LinkedList_Problem/delete_node/delete_node.c
Labels: hacktoberfest-accepted

#141 Adding Bank Management System
  Projects/C Projects/Bank Management System/Bank.C
  Projects/C Projects/Bank Management System/Readme.md
  Projects/C Projects/Bank Management System/images/1.png
  Projects/C Projects/Bank Management System/images/10.png
  Projects/C Projects/Bank Management System/images/2.png
  Projects/C Projects/Bank Management System/images/3.png
  Projects/C Projects/Bank Management System/images/4.png
  Projects/C Projects/Bank Management System/images/5.png
  Projects/C Projects/Bank Management System/images/6.png
  Projects/C Projects/Bank Management System/images/7.png
  Projects/C Projects/Bank Management System/images/8.png
  Projects/C Projects/Bank Management System/images/9.png
Labels: hacktoberfest-accepted, hacktoberfest

#144 Added Find a sorted sub-sequence of size 4 in linear time cpp
  DSA/C++/Array_leetcode/Sub_Sequence.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#142 Insert Node in Linked List
  DSA/C/LinkedList_Problem/Insert node/Insert_node.c
Labels: hacktoberfest-accepted, hacktoberfest

#155 Add files via upload
  Compose Community/COMPOSE COMMUNITY TEMPLATE.pdf
Labels: hacktoberfest-accepted, hacktoberfest

#157 I added a calculator app
  Projects/Android-Development/Calculator/.gitignore
  Projects/Android-Development/Calculator/.idea/.gitignore
  Projects/Android-Development/Calculator/.idea/compiler.xml
  Projects/Android-Development/Calculator/.idea/gradle.xml
  Projects/Android-Development/Calculator/.idea/misc.xml
  Projects/Android-Development/Calculator/app/.gitignore
  Projects/Android-Development/Calculator/app/build.gradle
  Projects/Android-Development/Calculator/app/proguard-rules.pro
  Projects/Android-Development/Calculator/app/src/androidTest/java/com/myappcompany/calculator_2/ExampleInstrumentedTest.java
  Projects/Android-Development/Calculator/app/src/main/AndroidManifest.xml
  Projects/Android-Development/Calculator/app/src/main/java/com/myappcompany/calculator_2/MainActivity.java
  Projects/Android-Development/Calculator/app/src/main/java/com/myappcompany/calculator_2/SplashActivity.java
  Projects/Android-Development/Calculator/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Projects/Android-Development/Calculator/app/src/main/res/drawable/calculator.png
  Projects/Android-Development/Calculator/app/src/main/res/drawable/ic_launcher_background.xml
  Projects/Android-Development/Calculator/app/src/main/res/drawable/utube_logo.png
  Projects/Android-Development/Calculator/app/src/main/res/layout/activity_main.xml
  Projects/Android-Development/Calculator/app/src/main/res/layout/activity_splash.xml
  Projects/Android-Development/Calculator/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Projects/Android-Development/Calculator/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Projects/Android-Development/Calculator/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  Projects/Android-Development/Calculator/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  Projects/Android-Development/Calculator/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  Projects/Android-Development/Calculator/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  Projects/Android-Development/Calculator/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  Projects/Android-Development/Calculator/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  Projects/Android-Development/Calculator/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  Projects/Android-Development/Calculator/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  Projects/Android-Development/Calculator/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  Projects/Android-Development/Calculator/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  Projects/Android-Development/Calculator/app/src/main/res/values-night/themes.xml
  Projects/Android-Development/Calculator/app/src/main/res/values/colors.xml
  Projects/Android-Development/Calculator/app/src/main/res/values/strings.xml
  Projects/Android-Development/Calculator/app/src/main/res/values/themes.xml
  Projects/Android-Development/Calculator/app/src/main/res/xml/backup_rules.xml
  Projects/Android-Development/Calculator/app/src/main/res/xml/data_extraction_rules.xml
  Projects/Android-Development/Calculator/app/src/test/java/com/myappcompany/calculator_2/ExampleUnitTest.java
  Projects/Android-Development/Calculator/build.gradle
  Projects/Android-Development/Calculator/gradle.properties
  Projects/Android-Development/Calculator/gradle/wrapper/gradle-wrapper.jar
  Projects/Android-Development/Calculator/gradle/wrapper/gradle-wrapper.properties
  Projects/Android-Development/Calculator/gradlew
  Projects/Android-Development/Calculator/gradlew.bat
  Projects/Android-Development/Calculator/settings.gradle
Labels: hacktoberfest-accepted, hacktoberfest

#153 Linear Search Algorithm Added
  DSA/JAVA/Algorithms/LinearSearch/LinearSearch.java
  DSA/JAVA/Algorithms/LinearSearch/Readme.md
Labels: hacktoberfest-accepted, hacktoberfest

#149 Added ReadMe
  DSA/C++/ALgorithm/Geometry Based/README.md
  DSA/C++/ALgorithm/Geometry Based/Skyline Heights(Geometry Based Problem).cpp
  DSA/C++/ALgorithm/Heap/HeapCreation.cpp
  DSA/C++/ALgorithm/Heap/README.md
Labels: hacktoberfest-accepted, hacktoberfest

#148 Adding a Drum-Kit Website
  Projects/Frontend Projects/Drum Kit Website/images/crash.png
  Projects/Frontend Projects/Drum Kit Website/images/kick.png
  Projects/Frontend Projects/Drum Kit Website/images/snare.png
  Projects/Frontend Projects/Drum Kit Website/images/tom1.png
  Projects/Frontend Projects/Drum Kit Website/images/tom2.png
  Projects/Frontend Projects/Drum Kit Website/images/tom3.png
  Projects/Frontend Projects/Drum Kit Website/images/tom4.png
  Projects/Frontend Projects/Drum Kit Website/index.html
  Projects/Frontend Projects/Drum Kit Website/index.js
  Projects/Frontend Projects/Drum Kit Website/sounds/crash.mp3
  Projects/Frontend Projects/Drum Kit Website/sounds/kick-bass.mp3
  Projects/Frontend Projects/Drum Kit Website/sounds/snare.mp3
  Projects/Frontend Projects/Drum Kit Website/sounds/tom-1.mp3
  Projects/Frontend Projects/Drum Kit Website/sounds/tom-2.mp3
  Projects/Frontend Projects/Drum Kit Website/sounds/tom-3.mp3
  Projects/Frontend Projects/Drum Kit Website/sounds/tom-4.mp3
  Projects/Frontend Projects/Drum Kit Website/styles.css
Labels: hacktoberfest-accepted, hacktoberfest

#167 Create Candies.java
  DSA/JAVA/Array_LeetCode/Candies.java
Labels: hacktoberfest-accepted, hacktoberfest

#168 Sonal modi git maximum wealth
  DSA/JAVA/Array_LeetCode/MaximumWealth.java
Labels: hacktoberfest-accepted, hacktoberfest

#169 Sonal modi git sort
  DSA/JAVA/Array_LeetCode/SortColors.java
Labels: hacktoberfest-accepted, hacktoberfest

#170 Adding trapping rain water problem
  DSA/C++/Array_leetcode/42_Trappimg_rainwater_problem.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#176 Update Readme.md
  Hacktoberfest/Readme.md
Labels: hacktoberfest-accepted, hacktoberfest

#177 Create MissingNumber.java
  DSA/JAVA/Sorting_LeetCode/MissingNumber.java
Labels: hacktoberfest-accepted, hacktoberfest

#172 Adding longest consecutive sequence
  DSA/C++/Array_leetcode/128_Longest_Consecutive_Sequence.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#163 Add Travel-journal using ReactJS
  Projects/Frontend Projects/Travel-journal using ReactJS/.gitignore
  Projects/Frontend Projects/Travel-journal using ReactJS/README.md
  Projects/Frontend Projects/Travel-journal using ReactJS/package-lock.json
  Projects/Frontend Projects/Travel-journal using ReactJS/package.json
  Projects/Frontend Projects/Travel-journal using ReactJS/public/index.html
  Projects/Frontend Projects/Travel-journal using ReactJS/public/manifest.json
  Projects/Frontend Projects/Travel-journal using ReactJS/public/robots.txt
  Projects/Frontend Projects/Travel-journal using ReactJS/src/App.css
  Projects/Frontend Projects/Travel-journal using ReactJS/src/App.js
  Projects/Frontend Projects/Travel-journal using ReactJS/src/App.test.js
  Projects/Frontend Projects/Travel-journal using ReactJS/src/Card.js
  Projects/Frontend Projects/Travel-journal using ReactJS/src/australia.jpg
  Projects/Frontend Projects/Travel-journal using ReactJS/src/data.js
  Projects/Frontend Projects/Travel-journal using ReactJS/src/index.css
  Projects/Frontend Projects/Travel-journal using ReactJS/src/index.js
  Projects/Frontend Projects/Travel-journal using ReactJS/src/japan.jpg
  Projects/Frontend Projects/Travel-journal using ReactJS/src/location.png
  Projects/Frontend Projects/Travel-journal using ReactJS/src/logo.svg
  Projects/Frontend Projects/Travel-journal using ReactJS/src/norway.jpg
  Projects/Frontend Projects/Travel-journal using ReactJS/src/reportWebVitals.js
  Projects/Frontend Projects/Travel-journal using ReactJS/src/setupTests.js
Labels: hacktoberfest-accepted, hacktoberfest

#162 Adding Tin-Dog Website
  Projects/Frontend Projects/Tin-Dog-Website/README.md
  Projects/Frontend Projects/Tin-Dog-Website/css/styles.css
  Projects/Frontend Projects/Tin-Dog-Website/images/TechCrunch.png
  Projects/Frontend Projects/Tin-Dog-Website/images/bizinsider.png
  Projects/Frontend Projects/Tin-Dog-Website/images/dog-img.jpg
  Projects/Frontend Projects/Tin-Dog-Website/images/iphone6.png
  Projects/Frontend Projects/Tin-Dog-Website/images/lady-img.jpg
  Projects/Frontend Projects/Tin-Dog-Website/images/mashable.png
  Projects/Frontend Projects/Tin-Dog-Website/images/tnw.png
  Projects/Frontend Projects/Tin-Dog-Website/index.html
Labels: hacktoberfest-accepted, hacktoberfest

#189 Adding sort colors
  DSA/C++/Array_leetcode/15_3Sum.cpp
  DSA/C++/Array_leetcode/75_Sort Colors.cpp
  DSA/JAVA/Array_LeetCode/11_Container with most Water.java
  DSA/JAVA/Array_LeetCode/48_Rotate Image.java
Labels: hacktoberfest-accepted, hacktoberfest

#191 Update ArrayForm.java
  DSA/JAVA/Array_LeetCode/ArrayForm.java
Labels: hacktoberfest-accepted, hacktoberfest

#192 Add files via upload
  DSA/Sorting/cyclicSort.java
Labels: hacktoberfest-accepted, hacktoberfest

#193 Ranganmukherjee patch 2
  DSA/JAVA/Array_LeetCode/firstocc_lastocc.java
Labels: hacktoberfest-accepted, hacktoberfest

#194 Gagan8161 patch 2
  DSA/Array/RotateArray.java
Labels: hacktoberfest-accepted, hacktoberfest

#195 Ranganmukherjee patch 3
  DSA/JAVA/Array_LeetCode/find_an_ele_in_rotated_sorted_array.java
Labels: hacktoberfest-accepted, hacktoberfest

#196 Ranganmukherjee patch 4
  DSA/JAVA/Array_LeetCode/duplicate.java
Labels: hacktoberfest-accepted, hacktoberfest

#197 Create MissingNumber_sorting.java
  DSA/JAVA/Sorting_LeetCode/MissingNumber_sorting.java
Labels: hacktoberfest-accepted, hacktoberfest

#198 Gagan8161 patch 9
  DSA/JAVA/Sorting_LeetCode/HeightChecker_sorting.java
Labels: hacktoberfest-accepted, hacktoberfest

#200 Created-Tic-Tac-Toe-Game
  Projects/Frontend Projects/Tic Tac Toe/bgImg.jpg
  Projects/Frontend Projects/Tic Tac Toe/excited.gif
  Projects/Frontend Projects/Tic Tac Toe/index.html
  Projects/Frontend Projects/Tic Tac Toe/music.wav
  Projects/Frontend Projects/Tic Tac Toe/script.js
  Projects/Frontend Projects/Tic Tac Toe/style.css
Labels: hacktoberfest-accepted, hacktoberfest

#199 Adding_Two_Number_LinkedList
  DSA/C++/LinkedList_LeetCode/Adding_Two_Number_LL
Labels: hacktoberfest-accepted, hacktoberfest

#178 41. First Missing Positive
  DSA/C++/Array_leetcode/41. First Missing Positive
Labels: hacktoberfest-accepted, hacktoberfest

#185 Added KMP Algorithm under DSA/C++
  DSA/C++/ALgorithm/KMP Algorithm/KMP Algorithm.cpp
  DSA/C++/ALgorithm/KMP Algorithm/Readme.md
Labels: hacktoberfest-accepted, hacktoberfest

#204 Aggresive_Cows_Problem
  DSA/C++/Array_leetcode/Aggresive_Cows_Problem
Labels: hacktoberfest-accepted, hacktoberfest

#202 Created a Body Mass Index (BMI) Calculator
  Projects/Javascript Projects/BMI Calculator/ReadMe.md
  Projects/Javascript Projects/BMI Calculator/index.html
  Projects/Javascript Projects/BMI Calculator/main.css
  Projects/Javascript Projects/BMI Calculator/script.js
Labels: hacktoberfest-accepted, hacktoberfest

#156 java selection sort added
  DSA/JAVA/Algorithms/Selection Sort/Selection sort.md
Labels: hacktoberfest-accepted, hacktoberfest

#207 Gradient Generator
  Projects/React_Project/Gradient_Generator/README.md
  Projects/React_Project/Gradient_Generator/package-lock.json
  Projects/React_Project/Gradient_Generator/package.json
  Projects/React_Project/Gradient_Generator/public/favicon.ico
  Projects/React_Project/Gradient_Generator/public/index.html
  Projects/React_Project/Gradient_Generator/public/logo192.png
  Projects/React_Project/Gradient_Generator/public/logo512.png
  Projects/React_Project/Gradient_Generator/public/manifest.json
  Projects/React_Project/Gradient_Generator/public/robots.txt
  Projects/React_Project/Gradient_Generator/src/App.js
  Projects/React_Project/Gradient_Generator/src/App.test.js
  Projects/React_Project/Gradient_Generator/src/components/Card.jsx
  Projects/React_Project/Gradient_Generator/src/components/Color_Combinations.js
  Projects/React_Project/Gradient_Generator/src/components/FlagCard.jsx
  Projects/React_Project/Gradient_Generator/src/components/Footer.jsx
  Projects/React_Project/Gradient_Generator/src/components/GeneratorComp.jsx
  Projects/React_Project/Gradient_Generator/src/components/Header.jsx
  Projects/React_Project/Gradient_Generator/src/components/Navbar.jsx
  Projects/React_Project/Gradient_Generator/src/index.css
  Projects/React_Project/Gradient_Generator/src/index.js
  Projects/React_Project/Gradient_Generator/src/logo.svg
  Projects/React_Project/Gradient_Generator/src/pages/Favourite.jsx
  Projects/React_Project/Gradient_Generator/src/pages/Flags.jsx
  Projects/React_Project/Gradient_Generator/src/pages/Generator.jsx
  Projects/React_Project/Gradient_Generator/src/pages/Home.jsx
  Projects/React_Project/Gradient_Generator/src/reportWebVitals.js
  Projects/React_Project/Gradient_Generator/src/setupTests.js
  Projects/React_Project/Gradient_Generator/tailwind.config.js
Labels: hacktoberfest-accepted, hacktoberfest

#206 Unsplash Clone
  Projects/React_Project/README.md
  Projects/React_Project/UnsplashClone/README.md
  Projects/React_Project/UnsplashClone/package-lock.json
  Projects/React_Project/UnsplashClone/package.json
  Projects/React_Project/UnsplashClone/public/favicon.ico
  Projects/React_Project/UnsplashClone/public/index.html
  Projects/React_Project/UnsplashClone/public/l1.ico
  Projects/React_Project/UnsplashClone/public/l2.ico
  Projects/React_Project/UnsplashClone/public/l3.ico
  Projects/React_Project/UnsplashClone/public/logo192.png
  Projects/React_Project/UnsplashClone/public/logo512.png
  Projects/React_Project/UnsplashClone/public/manifest.json
  Projects/React_Project/UnsplashClone/public/robots.txt
  Projects/React_Project/UnsplashClone/public/unsplash.ico
  Projects/React_Project/UnsplashClone/src/App.js
  Projects/React_Project/UnsplashClone/src/App.test.js
  Projects/React_Project/UnsplashClone/src/components/Header.jsx
  Projects/React_Project/UnsplashClone/src/components/Image.jsx
  Projects/React_Project/UnsplashClone/src/components/Navbar.jsx
  Projects/React_Project/UnsplashClone/src/components/Spinner.jsx
  Projects/React_Project/UnsplashClone/src/index.css
  Projects/React_Project/UnsplashClone/src/index.js
  Projects/React_Project/UnsplashClone/src/logo.svg
  Projects/React_Project/UnsplashClone/src/pages/Home.jsx
  Projects/React_Project/UnsplashClone/src/pages/NavPages.jsx
  Projects/React_Project/UnsplashClone/src/reportWebVitals.js
  Projects/React_Project/UnsplashClone/src/setupTests.js
  Projects/React_Project/UnsplashClone/src/unsplash.jsx
  Projects/React_Project/UnsplashClone/tailwind.config.js
Labels: hacktoberfest-accepted, hacktoberfest

#208 A basic current weather website
  Projects/Frontend Projects/CurrentWeather/ReadMe.md
  Projects/Frontend Projects/CurrentWeather/app.js
  Projects/Frontend Projects/CurrentWeather/index.html
  Projects/Frontend Projects/CurrentWeather/styles.css
Labels: hacktoberfest-accepted, hacktoberfest

#216 Create Spiral Print.cpp
  DSA/C++/Array_leetcode/Spiral Print.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#218 RotateArray.cpp
  DSA/C++/Array_leetcode/RotateArray.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#215 Simple calculator added
  Projects/Python_Projects/Simple Calculator/main.py
Labels: hacktoberfest-accepted, hacktoberfest

#220 MergeTwoSortedLL.cpp
  DSA/C++/ALgorithm/Linked List/MergeTwoSortedLL.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#227 Create Pangram.java
  DSA/JAVA/Array_LeetCode/Pangram.java
Labels: hacktoberfest-accepted, hacktoberfest

#228 Create UniqueUptoZero.java
  DSA/JAVA/Array_LeetCode/UniqueUptoZero.java
Labels: hacktoberfest-accepted, hacktoberfest

#229 Debahuti2000 patch 2
  DSA/JAVA/Array_LeetCode/ReshapeTheMatrix.java
Labels: hacktoberfest-accepted, hacktoberfest

#230 Debahuti2000 patch 3
  DSA/JAVA/Set_Matrix_Zero.java
Labels: hacktoberfest-accepted, hacktoberfest

#231 Debahuti2000 patch 4
  DSA/JAVA/Array_LeetCode/NumberOfGoodPairs.java
Labels: hacktoberfest-accepted, hacktoberfest
