Repository risingstar-bit/Compose-Community, pull requests merged in 2023-10, with the labels that each got.

#233 Create 141_Linked_list_cycle.cpp
  DSA/C++/LinkedList_LeetCode/141_Linked_list_cycle.cpp
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#234 Create 46_Permutations.cpp
  DSA/C++/Array_leetcode/46_Permutations.cpp
Labels: hacktoberfest-accepted, hacktoberfest, beginner

#237 Create 50_Pow(x, n).cpp
  DSA/C++/Math_DSA/50_Pow(x, n).cpp
Labels: hacktoberfest-accepted, hacktoberfest, beginner

#235 Create 410_Split_array_largest_sum.cpp
  DSA/C++/ALgorithm/BinarySearchTree/BFS/410_Split_array_largest_sum.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#240 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#241 Update README.md
  README.md
Labels: hacktoberfest-accepted, beginner, Hacktoberfest 2023

#242 Create GCD.java
  DSA/JAVA/Math_DSA/GCD.java
Labels: hacktoberfest-accepted, hacktoberfest

#243 added my project
  Projects/Frontend Projects/sign_up_page/index.html
  Projects/Frontend Projects/sign_up_page/style.css
Labels: hacktoberfest-accepted, hacktoberfest, beginner

#245 Update Readme.md
  Hacktoberfest/Readme.md
Labels: hacktoberfest-accepted, Hacktoberfest 2023

#247 Rename Selection sort.md to Readme.md
  DSA/JAVA/Algorithms/Selection Sort/Readme.md
Labels: hacktoberfest-accepted, Hacktoberfest 2023

#248 Create Readme.md
  DSA/JAVA/Algorithms/Bubble Sort/Readme.md
Labels: hacktoberfest-accepted, Hacktoberfest 2023

#249 Update Readme.md
  DSA/JAVA/Algorithms/Bubble Sort/Readme.md
Labels: hacktoberfest-accepted, hacktoberfest

#250 added my project
  DSA/C++/Recursion/5_Remove_duplicates_from_a_sorted_array.cpp
  Projects/Frontend Projects/Little_taco_shop/contact.html
  Projects/Frontend Projects/Little_taco_shop/css/style.css
  Projects/Frontend Projects/Little_taco_shop/favicon.ico
  Projects/Frontend Projects/Little_taco_shop/hours.html
  Projects/Frontend Projects/Little_taco_shop/img/tacos_and_drink_400x267.png
  Projects/Frontend Projects/Little_taco_shop/img/tacos_close_up_400x260.png
  Projects/Frontend Projects/Little_taco_shop/img/tacos_tray_400x267.png
  Projects/Frontend Projects/Little_taco_shop/index.html
  Projects/Machine Learning/Breast_cancer_using_machine_learning/breast_cancer.ipynb
Labels: hacktoberfest-accepted, Hacktoberfest 2023

#256 i added insertion_sort code
  DSA/JAVA/Algorithms/INSERTION_SORT/insertion_sort.c
Labels: hacktoberfest-accepted, hacktoberfest, beginner, Hacktoberfest 2023

#257 Create README.md
  DSA/JAVA/Algorithms/INSERTION_SORT/README.md
Labels: hacktoberfest-accepted, hacktoberfest, Hacktoberfest 2023

#259 Formatting counter.c file added
  DSA/C/Problem_Statements/Formatting counter.c
  DSA/C/Problem_Statements/README.md
Labels: hacktoberfest-accepted, hacktoberfest

#261 Create countingsort.java
  DSA/JAVA/Algorithms/Counting_Sort/countingsort.java
Labels: hacktoberfest-accepted, beginner, Hacktoberfest 2023

#260 Create Library_code.py
  Projects/Python_Projects/Library_Management_System/code.py
Labels: hacktoberfest-accepted, Hacktoberfest 2023

#263 Create combination_sum.cpp
  DSA/C++/Recursion/combination_sum.cpp
Labels: hacktoberfest-accepted, Hacktoberfest 2023

#266 Create trapping_rainWater_queue.cpp
  DSA/C++/Queue_Deque_leetCode/trapping_rainWater_queue.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#265 Create start_loop.cpp
  DSA/C++/LinkedList_LeetCode/start_loop.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#264 Create stock_buy_sell.cpp
  DSA/C++/Array_leetcode/stock_buy_sell.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#275 i added quick_sort code
  DSA/C/ALGORITHM/SORTING/COUNT_SORT/count_sort.c
  DSA/C/ALGORITHM/SORTING/QUICK_SORT/.vscode/tasks.json
  DSA/C/ALGORITHM/SORTING/QUICK_SORT/quick_sort.c
  DSA/C/ALGORITHM/SORTING/QUICK_SORT/quick_sort.exe
Labels: hacktoberfest-accepted, hacktoberfest

#278 i added binary_search code
  DSA/C/ALGORITHM/SORTING/BINARY_SEARCH/binary_search.c
Labels: hacktoberfest-accepted, hacktoberfest
